jobs:
  - ${{ each module in parameters.modules }}:
    - job:
      displayName: ${{ format('tvOS {0}', module) }}
      pool:
        vmImage: internal-macos-10.15
      steps:
      - checkout: self
        submodules: recursive

      - task: Xcode@5
        displayName: Analyze
        inputs:
          actions: analyze
          xcWorkspacePath: AppCenter.xcworkspace
          scheme: '$(MODULE_TVOS) tvOS Framework'
          xcodeVersion: specifyPath
          xcodeDeveloperDir: '$(XCODE_PATH)'
          destinationPlatformOption: tvOS
          destinationSimulators: 'Apple TV 4K'

      - task: Xcode@5
        displayName: Test
        inputs:
          actions: test
          xcWorkspacePath: AppCenter.xcworkspace
          scheme: '$(MODULE_TVOS) tvOS Framework'
          xcodeVersion: specifyPath
          xcodeDeveloperDir: '$(XCODE_PATH)'
          destinationPlatformOption: tvOS
          destinationSimulators: 'Apple TV 4K'
          publishJUnitResults: true
        timeoutInMinutes: 10

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Diagnostic Reports'
        inputs:
          PathtoPublish: /Users/runner/Library/Logs/DiagnosticReports
          ArtifactName: 'Test Diagnostic Reports'
        condition: failed()

      - bash: 'bash <(curl -s https://codecov.io/bash) -X gcov -cF tvOS'
        displayName: 'Upload Coverage Report to Codecov'
