jobs:
  - ${{ each module in parameters.modules }}:
    - job:
      displayName: ${{ format('macOS {0}', module) }}
      pool:
        vmImage: internal-macos-10.15
      steps:
      - checkout: self
        submodules: recursive

      - task: Xcode@5
        displayName: Analyze
        inputs:
          actions: analyze
          xcWorkspacePath: AppCenter.xcworkspace
          scheme: '${{ module }} macOS Framework'
          xcodeVersion: specifyPath
          xcodeDeveloperDir: '$(XCODE_PATH)'
          destinationPlatformOption: macOS

      - task: Xcode@5
        displayName: Test
        inputs:
          actions: test
          xcWorkspacePath: AppCenter.xcworkspace
          scheme: '${{ module }} macOS Framework'
          xcodeVersion: specifyPath
          xcodeDeveloperDir: '$(XCODE_PATH)'
          destinationPlatformOption: macOS
          publishJUnitResults: true
        timeoutInMinutes: 10

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Diagnostic Reports'
        inputs:
          PathtoPublish: /Users/runner/Library/Logs/DiagnosticReports
          ArtifactName: 'Test Diagnostic Reports'
        condition: failed()

      - bash: 'bash <(curl -s https://codecov.io/bash) -X gcov -cF macOS'
        displayName: 'Upload Coverage Report to Codecov'
