parameters:
- name: modules
  type: object

steps:
- ${{ each module in parameters.modules }}:
  - task: Xcode@5
    displayName: ${{ format('Build {0} macOS Framework for Apple Silicon', module) }}
    inputs:
      xcWorkspacePath: AppCenter.xcworkspace
      scheme: '${{ module }} macOS Framework'
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '$(APPLE_SILICON_XCODE_PATH)'
      args: 'SYMROOT="$(Build.BinariesDirectory)"'

  - bash: |
      rm -rf "AppCenter-SDK-Apple/macOS/${{ module }}.framework"
      cp -R "$BUILD_BINARIESDIRECTORY/Release/${{ module }}.framework" "AppCenter-SDK-Apple/macOS"
      lipo -info "AppCenter-SDK-Apple/macOS/${{ module }}.framework/${{ module }}"

      rm -rf "AppCenter-SDK-Apple/XCFramework/${{ module }}.xcframework"
      for framework in $BUILD_BINARIESDIRECTORY/Release-xcframework/${{ module }}.xcframework/*/${{ module }}.framework; do
        xcframeworks+=( -framework "$framework")
      done
      xcodebuild -create-xcframework "${xcframeworks[@]}" -output "AppCenter-SDK-Apple/XCFramework/${{ module }}.xcframework"
      ls "AppCenter-SDK-Apple/XCFramework/${{ module }}.xcframework"
    displayName: ${{ format('Combine {0} Apple Silicon Binaries', module) }}
